CREATE TABLE "DBA"."AUD_PARAMETROS" (
	"PAR_NOMBRE" CHAR(76) NOT NULL,
	"PAR_DIRECCIION_1" CHAR(76) NULL,
	"PAR_DIRECCION_2" CHAR(76) NULL,
	"PAR_MTO_CUOT_ING" "T_MONEDA" NOT NULL,
	"PAR_ANO_FISCAL" TINYINT NULL,
	"PAR_ULTIMO_RECIBO" INTEGER NULL,
	"PAR_ULTIMO_RETIRO" INTEGER NULL,
	"PAR_ULTIMA_NC" INTEGER NULL,
	"PAR_ULTIMA_ND" INTEGER NULL,
	"PAR_TRABAJA_SABADO" TINYINT NULL,
	"PAR_CTA_CAJA" CHAR(20) NOT NULL,
	"PAR_FILIAL" TINYINT NOT NULL,
	"PAR_MTO_NOTA" "T_MONEDA" NULL,
	"PAR_NUM_PAGARE" INTEGER NULL,
	"PAR_FECHA_CAL_APOR" DATE NULL,
	"PAR_FECHA_CAL_NAVID" DATE NULL,
	"PAR_FECHA_CAL_RETIR" DATE NULL,
	"PAR_AGREGO" CHAR(10) NOT NULL DEFAULT CURRENT USER,
	"PAR_FECHA_AGR" DATE NOT NULL DEFAULT CURRENT DATE,
	"PAR_MODIFICO" CHAR(10) NULL,
	"PAR_FECHA_MOD" DATE NULL,
	"PAR_ULT_NUM_SOCIO" INTEGER NULL,
	"PAR_CUOTA_MENS" "T_MONEDA" NULL,
	"PAR_MENSAJE" CHAR(350) NULL,
	"PAR_MORA_2" "T_MONEDA" NULL,
	"PAR_CIUDAD" CHAR(20) NULL,
	"PAR_CTA_CAJA_EXT" CHAR(20) NULL,
	"PAR_ULT_FACTU" INTEGER NULL,
	"PAR_LOGO" LONG BINARY NULL,
	"PAR_SIGLAS" CHAR(20) NULL,
	"PAR_INV_CP" INTEGER NULL DEFAULT 0,
	"PAR_INV_MP" INTEGER NULL DEFAULT 0,
	"PAR_INV_LP" INTEGER NULL DEFAULT 0,
	"PAR_DPF_CP" INTEGER NULL DEFAULT 0,
	"PAR_DPF_MP" INTEGER NULL DEFAULT 0,
	"PAR_DPF_LP" INTEGER NULL DEFAULT 0,
	"PAR_LIB_GARANTIAS_DPF" TINYINT NULL DEFAULT 0,
	"PAR_LIBERA_AUT" TINYINT NULL DEFAULT 0,
	"PAR_DPF_COMPENSATORIO" INTEGER NULL DEFAULT 0,
	"PAR_AMORTIZA_DPF_COMP" TINYINT NULL DEFAULT 0,
	"PAR_LIQUIDA_CON_DPF" TINYINT NULL DEFAULT 0,
	"PAR_DIAS_PA_LIQUIDAR" INTEGER NULL DEFAULT 0,
	"PAR_RENOVAR_DPF_AUT" TINYINT NULL DEFAULT 0,
	"PAR_ISR" NUMERIC(7,2) NULL DEFAULT 0,
	"PAR_ISR_A_PARTIR" NUMERIC(15,2) NULL DEFAULT 0,
	"PAR_ISR_CTA_CONTA" CHAR(20) NULL,
	"PAR_CTA_FORMATSTRING" CHAR(30) NULL,
	"PAR_CTA_INPUTMASK" CHAR(30) NULL,
	"PAR_COMPANIA" TINYINT NOT NULL,
	"PAR_CRE_ATRA_DESDE" TINYINT NULL DEFAULT 0,
	"PAR_CRE_ATRA_HASTA" INTEGER NULL DEFAULT 0,
	"PAR_CRE_VENC" INTEGER NULL DEFAULT 0,
	"PAR_TERCERA_EDAD" TINYINT NULL DEFAULT 0,
	"PAR_INACTIVAR" TINYINT NULL DEFAULT 0,
	"PAR_INACTIVO_DESDE" TINYINT NULL DEFAULT 0,
	"PAR_LIQUIDA_CON_APORT" TINYINT NULL DEFAULT 0,
	"PAR_PRES_JUN" CHAR(40) NULL,
	"PAR_RECIBO" TINYINT NULL DEFAULT 0,
	"PAR_INACTIVO_AHORROS" TINYINT NULL DEFAULT 0,
	"PAR_PRESUPUESTO" TINYINT NULL DEFAULT 0,
	"PAR_ISR_CALCULAR" TINYINT NULL DEFAULT 0,
	"PAR_ISR_INCLUIR_BASE" TINYINT NULL DEFAULT 0,
	"PAR_CALCULO_INT" TINYINT NULL DEFAULT 0,
	"PAR_CTA_AHORROS" TINYINT NULL DEFAULT 0,
	"PAR_CTA_MENORES" TINYINT NULL DEFAULT 0,
	"PAR_CTA_NAVIDENOS" TINYINT NULL DEFAULT 0,
	"PAR_CTA_DOLARES" TINYINT NULL DEFAULT 0,
	"PAR_TRAS_CRE" TINYINT NULL,
	"PAR_ACT_TASA" TINYINT NULL DEFAULT 0,
	"PAR_AVAL_CRED" TINYINT NULL DEFAULT 0,
	"PAR_CTA_APORTACION" TINYINT NULL DEFAULT 0,
	"PAR_CTA_OTRAS" TINYINT NULL DEFAULT 0,
	"PAR_DIAS_NOT2" TINYINT NULL DEFAULT 0,
	"PAR_DIAS_NOT3" TINYINT NULL DEFAULT 0,
	"PAR_CAJA_VE_SALDO" TINYINT NULL DEFAULT 0,
	"PAR_TRAS_PROV" TINYINT NULL DEFAULT 0,
	"PAR_CTA_UNIRED" INTEGER NULL,
	"PAR_CTA_NOTAS" CHAR(20) NULL DEFAULT 0,
	"PAR_TIPO_SUELDO" INTEGER NULL DEFAULT 0,
	"PAR_CIERRE_DIARIO" TINYINT NULL DEFAULT 0,
	"PAR_CTA_GTO_COND" CHAR(20) NULL,
	"PAR_CTA_GTO_COND_ME" CHAR(20) NULL,
	"PAR_CTA_GTO_BANCO" CHAR(20) NULL,
	"PAR_OTROS_ING" CHAR(20) NULL,
	"PAR_ING_DIFERIDO" CHAR(20) NULL,
	"PAR_DIFERIDO" TINYINT NULL DEFAULT 0,
	"PAR_NC_COPIA_AVAL" TINYINT NULL DEFAULT 0,
	"PAR_EXC_MORA" TINYINT NULL DEFAULT 0,
	"PAR_RAHO_GTO" CHAR(20) NULL,
	"PAR_RAHO_ING" CHAR(20) NULL,
	"PAR_RCRE_GTO" CHAR(20) NULL,
	"PAR_RCRE_ING" CHAR(20) NULL,
	"PAR_RDPF_GTO" CHAR(20) NULL,
	"PAR_RDPF_ING" CHAR(20) NULL,
	"PAR_RINV_GTO" CHAR(20) NULL,
	"PAR_RINV_ING" CHAR(20) NULL,
	"PAR_PTMO_READECUACION" TINYINT NULL DEFAULT 0,
	"PAR_DIAS_INTS_CXC" TINYINT NULL DEFAULT 90,
	"PAR_TPII_AHO" INTEGER NULL DEFAULT 0,
	"PAR_TPII_APO" INTEGER NULL DEFAULT 0,
	"PAR_LIQUIDA_CON_AHOR" TINYINT NULL,
	"PAR_FOR_CHEQUE" TINYINT NULL DEFAULT 0,
	"PAR_FOR_LIBRETA" TINYINT NULL DEFAULT 0,
	"PAR_FOR_RECIBOS" TINYINT NULL DEFAULT 0,
	"PAR_FOR_NOTASCOBRO" TINYINT NULL DEFAULT 0,
	"PAR_FOR_TITULOS" TINYINT NULL DEFAULT 0,
	"PAR_CAJA_RESERVA" VARCHAR(20) NULL,
	"PAR_COOP_AUT" TINYINT NULL DEFAULT 1,
	"PAR_FREC_PAGO" TINYINT NULL DEFAULT 0,
	"PAR_PAGARE" TINYINT NULL DEFAULT 0,
	"PAR_AUT_AUTOMATICO" TINYINT NULL,
	"PAR_CLAVE_AUT" CHAR(20) NULL,
	"PAR_CAJA_RES_DOLAR" CHAR(20) NULL,
	"PAR_FOR_SOLFID" TINYINT NULL DEFAULT 0,
	"PAR_FOR_DIST_EXC" TINYINT NULL DEFAULT 0,
	"PAR_FOR_SOLING" TINYINT NULL DEFAULT 0,
	"PAR_FOR_FACTURA" TINYINT NULL DEFAULT 0,
	"PAR_FOR_CONTRATO" TINYINT NULL DEFAULT 0,
	"PAR_INGRESOS_MIN" NUMERIC(10,2) NULL,
	"PAR_NUM_DEPENDIENTES" TINYINT NULL,
	"PAR_INICIO_INTERVALO" NUMERIC(10,2) NULL,
	"PAR_LIMITE_INTERVALO" NUMERIC(10,2) NULL,
	"PAR_TAMANO_INTERVALO" NUMERIC(10,2) NULL,
	"PAR_TASA_AHORRO" NUMERIC(10,2) NULL,
	"PAR_TASA_PRESTAMO" NUMERIC(10,2) NULL,
	"PAR_COBERTURA_EQUI_AHO" NUMERIC(10,2) NULL,
	"PAR_COBERTURA_EQUI_PREST" NUMERIC(10,2) NULL,
	"PAR_LIBRETA_NUM" TINYINT NULL,
	"PAR_CTA_IHSS" VARCHAR(20) NULL,
	"PAR_MTO_ALERTA" NUMERIC(9,2) NULL DEFAULT 0,
	"PAR_FOR_RETIRO_AHO" TINYINT NULL DEFAULT 0,
	"PAR_CALC_MORA" TINYINT NULL DEFAULT 0,
	"PAR_SORTEO" TINYINT NOT NULL DEFAULT 0,
	"PAR_RURAL" TINYINT NULL,
	"PAR_TRABAJA_INHABILES" TINYINT NULL,
	"PAR_APLICA_APORT" NUMERIC(2,0) NULL DEFAULT 6,
	"PAR_PORC_SEGURO" NUMERIC(4,2) NULL DEFAULT 0,
	"PAR_MTO_ALERTA_ME" NUMERIC(9,2) NULL DEFAULT 6,
	"PAR_MTO_REMESA_ME" NUMERIC(9,2) NULL DEFAULT 6,
	"PAR_ESTADOS_GRAFICADOS" TINYINT NULL,
	"PAR_MONTO_AHORROS" NUMERIC(5,2) NULL,
	"PAR_INACTIVA_CUENTAS" TINYINT NULL,
	"PAR_CUOTA_DICIEMBRE" NUMERIC(5,2) NULL,
	"PAR_PROV_AUTOMATICOS" INTEGER NULL DEFAULT 90,
	"PAR_PROV_GRECIPROCRA" INTEGER NULL DEFAULT 180,
	"PAR_MONTOINGRESOS" NUMERIC(5,2) NULL,
	"PAR_MTO_ALERTA2_ME" NUMERIC(9,2) NULL DEFAULT 0,
	"PAR_CAI" VARCHAR(40) NULL,
	"PAR_RANGO_I" INTEGER NULL,
	"PAR_RANGO_F" INTEGER NULL,
	"PAR_ULTIMA_FACTURA" INTEGER NULL,
	"PAR_FECH_FACT_F" DATE NULL,
	"PAR_RTN" VARCHAR(16) NULL,
	"PAR_CORREO" VARCHAR(80) NULL,
	"PAR_PORC_SEGU_APOR" NUMERIC(5,2) NULL,
	"PAR_ISR_CALCULAR_APO" TINYINT NULL DEFAULT 0,
	"PAR_CTA_RES_CAP" CHAR(20) NULL,
	"PAR_CTA_RES_INT" CHAR(20) NULL,
	"PAR_CAS_CTA_ANT" CHAR(20) NULL,
	"PAR_CAS_CTA_ACT" CHAR(20) NULL,
	"PAR_CAS_CON_CONTA" CHAR(20) NULL,
	"PAR_CAS_ING_ANT" CHAR(20) NULL,
	"PAR_CAS_ING_ACT" CHAR(20) NULL,
	"PAR_CASTIGAR_C" TINYINT NULL DEFAULT 0,
	"PAR_CTA_GASTOC" CHAR(20) NULL,
	"PAR_APORT_OBLIGA_CRED" TINYINT NULL,
	"PAR_COBRA_APO_INAC" TINYINT NULL DEFAULT 0,
	"PAR_MONTO_COBRO_APO" NUMERIC(15,2) NULL DEFAULT 0,
	"PAR_CTA_COBRO_APO" CHAR(20) NULL,
	"PAR_TIPO_INST_UIF" INTEGER NULL,
	"PAR_COD_INST_UIF" INTEGER NULL,
	"PAR_MTO_TRANS_MULTIPLES" NUMERIC(9,2) NULL,
	"PAR_CIERRE_OFFLINE" TINYINT NULL DEFAULT 0,
	"PAR_SEGUROS" INTEGER NULL DEFAULT 0,
	"PAR_MTO_REMESAS" NUMERIC(9,2) NULL,
	"PAR_DEBITO_RETI_CUO_APOR" TINYINT NULL,
	"PAR_EDAD_MAXIMA_CTA_MENOR" INTEGER NULL,
	"PAR_CANT_PRESTAMOS_AUT" INTEGER NULL,
	"PAR_CTA_PRESTAMOS_AUT" INTEGER NULL,
	"PAR_CANT_MOV_CAJA_SOSPECHOSOS" INTEGER NULL,
	"PAR_TRASL_INHABILES" INTEGER NULL DEFAULT 0,
	"PAR_AUTORIZACION" TINYINT NULL DEFAULT 1,
	"ACCION" CHAR(1) NULL,
	"TIEMPO" TIMESTAMP NULL,
	"HECHO" VARCHAR(16) NULL
) IN "system";

CREATE TABLE "DBA"."TIPOS_VALES" (
	"TVA_SEQ" INTEGER NOT NULL,
	"TVA_CODIGO" INTEGER NOT NULL,
	"TVA_DESCRIPCION" VARCHAR(100) NOT NULL,
	"TVA_AGREGO" VARCHAR(10) NOT NULL,
	"TVA_FECHA_AGR" TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
	"TVA_MODIFICO" VARCHAR(10) NULL,
	"TVA_FECHA_MOD" TIMESTAMP NULL DEFAULT TIMESTAMP,
	"TVA_FILIAL" TINYINT NOT NULL,
	"TVA_COMPANIA" TINYINT NOT NULL,
	"TVA_CTA_CONTABLE" CHAR(20) NULL,
	"TVA_MONTO" NUMERIC(18,2) NULL
) IN "system";

CREATE TRIGGER "trg_upd_tipo_vales" before update order 2 on
DBA.TIPOS_VALES
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.TVA_MODIFICO=current user;
  set new_name.TVA_FECHA_MOD=current timestamp
end;
CREATE TRIGGER "TRG_INS_TIPO_VALES" before insert order 1 on
DBA.TIPOS_VALES
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial integer;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.TVA_FILIAL=filial;
  set new_name.TVA_COMPANIA=compania;
  select func_llaves('TIPOS_VALES.TVA_SEQ',filial) into numero from SYS.DUMMY;
  set new_name.TVA_SEQ=numero;
  set new_name.TVA_AGREGO=current user;
  set new_name.TVA_FECHA_AGR=current timestamp
end;


CREATE TABLE "DBA"."VALES_X_CLIENTE" (
	"VXC_SEQ" INTEGER NOT NULL,
	"VXC_CODIGO_VALE" INTEGER NOT NULL,
	"VXC_CODIGO_CLIENTE" INTEGER NOT NULL,
	"VXC_TIPO_VALE" INTEGER NOT NULL,
	"VXC_MONTO_VALE" NUMERIC(18,2) NULL,
	"VXC_SALDO_VALE" NUMERIC(18,2) NULL,
	"VXC_AGREGO" VARCHAR(10) NOT NULL,
	"VXC_FECHA_AGR" TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
	"VXC_MODIFICO" VARCHAR(10) NULL,
	"VXC_FECHA_MOD" TIMESTAMP NULL DEFAULT TIMESTAMP,
	"VXC_FILIAL" TINYINT NOT NULL,
	"VXC_COMPANIA" TINYINT NOT NULL,
	"VXC_VALIDO_DESDE" DATE NULL,
	"VXC_VALIDO_HASTA" DATE NULL,
	"VXC_ESTADO" INTEGER NULL
) IN "system";

CREATE TRIGGER "trg_upd_tipo_vales" before update order 2 on
DBA.VALES_X_CLIENTE
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.VXC_MODIFICO=current user;
  set new_name.VXC_FECHA_MOD=current timestamp
end;
CREATE TRIGGER "TRG_INS_VALES_CLIENTE" before insert order 1 on
DBA.VALES_X_CLIENTE
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial integer;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.VXC_FILIAL=filial;
  set new_name.VXC_COMPANIA=compania;
  select func_llaves('VALES_X_CLIENTE.VXC_SEQ',filial) into numero from SYS.DUMMY;
  set new_name.VXC_SEQ=numero;
  set new_name.VXC_AGREGO=current user;
  set new_name.VXC_FECHA_AGR=current timestamp
end;






CREATE TABLE "DBA"."Cobro_x_Vale" (
	"CXV_SEQ" INTEGER NOT NULL,
	"CXV_NUM_SALIDA" INTEGER NOT NULL,
	"CXV_FECHA" DATE NOT NULL,
	"CXV_CODIGO_VALE" INTEGER NOT NULL,
	"CXV_NUM_PDA" INTEGER NOT NULL,
	"CXV_MONTO_EFECTIVO" NUMERIC(18,2) NULL,
	"CXV_MONTO_VALE" NUMERIC(18,2) NULL,
	"CXV_ESTADO" VARCHAR(2) NOT NULL,
	"CXV_AGREGO" VARCHAR(10) NOT NULL,
	"CXV_FECHA_AGR" TIMESTAMP NOT NULL DEFAULT TIMESTAMP,
	"CXV_MODIFICO" VARCHAR(10) NULL,
	"CXV_FECHA_MOD" TIMESTAMP NULL DEFAULT TIMESTAMP,
	"CXV_FILIAL" TINYINT NOT NULL,
	"CXV_COMPANIA" TINYINT NOT NULL
) IN "system";

CREATE TRIGGER "trg_upd_COBRO_VALE" before update order 2 on
DBA.Cobro_x_Vale
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.CXV_MODIFICO=current user;
  set new_name.CXV_FECHA_MOD=current timestamp
end;

CREATE TRIGGER "TRG_INS_COBRO_VALE" before insert order 1 on
DBA.Cobro_x_Vale
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial integer;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.CXV_FILIAL=filial;
  set new_name.CXV_COMPANIA=compania;
  select func_llaves('VALES_X_CLIENTE.CXV_SEQ',filial) into numero from SYS.DUMMY;
  set new_name.CXV_SEQ=numero;
  set new_name.CXV_AGREGO=current user;
  set new_name.CXV_FECHA_AGR=current timestamp
end;



CREATE TABLE "DBA"."F_CRED_TASA_MORA" (
	"TM_SECUENCIA" INTEGER NOT NULL UNIQUE,
	"TM_CUENTA" INTEGER NOT NULL,
	"TM_FECHA" DATE NOT NULL,
	"TM_TASA" DOUBLE NOT NULL DEFAULT 0,
	"TM_FILIAL" INTEGER NOT NULL,
	"TM_COMPANIA" TINYINT NOT NULL,
	"TM_AGREGO" CHAR(10) NULL,
	"TM_FECHA_AGR" DATE NULL,
	"TM_MODIFICO" CHAR(10) NULL,
	"TM_FECHA_MOD" DATE NULL,
	PRIMARY KEY ( "TM_CUENTA" ASC, "TM_COMPANIA" ASC )
) IN "system";


CREATE TRIGGER "trg_upd_tasa_mora" before update order 2 on
DBA.F_CRED_TASA_MORA
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.TM_MODIFICO = current user;
  set new_name.TM_FECHA_MOD = current date
end;
CREATE TRIGGER "trg_ins_tasa_mora" before insert order 1 on
DBA.F_CRED_TASA_MORA
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial smallint;
  declare COMPANIA smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.TM_FILIAL = filial;
  set new_name.TM_COMPANIA = COMPANIA;
  select func_llaves('F_CRED_TASA_MORA.TM_SECUENCIA',filial) into numero from SYS.DUMMY;
  set new_name.TM_SECUENCIA = numero;
  set new_name.TM_AGREGO = current user;
  set new_name.TM_FECHA_AGR = current date
end;


CREATE TABLE "DBA"."F_Lotes" (
	"LOT_SEQ" INTEGER NOT NULL UNIQUE,
	"LOT_LOTE" INTEGER NOT NULL,
	"LOT_COD_PROD" CHAR(15) NOT NULL,
	"LOT_COD_BARRA" VARCHAR(100) NULL,
	"LOT_FILIAL" TINYINT NOT NULL,
	"LOT_COMPANIA" TINYINT NOT NULL,
	"LOT_AGREGO" CHAR(10) NOT NULL DEFAULT CURRENT USER,
	"LOT_FECHA_AGREGO" DATE NOT NULL DEFAULT CURRENT DATE,
	"LOT_MODIFICO" CHAR(10) NULL,
	"LOT_FECHA_MODIFICO" DATE NULL,
	"LOT_EXISTENCIA" NUMERIC(10,0) NULL,
	"LOT_FECHA" DATE NULL,
	PRIMARY KEY ( "LOT_SEQ" ASC, "LOT_LOTE" ASC, "LOT_FILIAL" ASC, "LOT_COMPANIA" ASC )
) IN "system";

CREATE TRIGGER "trg_upd_f_lotes" before update order 2 on
DBA.F_Lotes
referencing old as old_name new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.LOT_MODIFICO=current user;
  set new_name.LOT_FECHA_MODIFICO=current date
end;

CREATE TRIGGER "trg_ins_lote" before insert order 1 on
DBA.F_Lotes
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial smallint;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.LOT_FILIAL =filial;
  set new_name.LOT_COMPANIA =compania;
  select func_llaves('F_Lotes.LOT_SEQ',filial) into numero from SYS.DUMMY;
  set new_name.LOT_SEQ=numero;
  set new_name.LOT_AGREGO=current user;
  set new_name.LOT_FECHA_AGREGO=current date
end;

CREATE TABLE "DBA"."H_DETALLE_HORARIOS" (
	"HD_CODIGO_EMPRESA" INTEGER NOT NULL,
	"HD_CODIGO_AGENCIA" INTEGER NOT NULL,
	"HD_CODIGO_HORARIO" INTEGER NOT NULL,
	"HD_DIA" NUMERIC(1,0) NOT NULL,
	"HD_HORA_ENTRADA" "datetime" NULL,
	"HD_HORA_SALIDA" "datetime" NULL,
	"HD_HORA_MAXIMA_DIURNA" "datetime" NULL,
	"HD_HORA_MAXIMA_NOCTURNA" "datetime" NULL,
	"HD_PORCENTAJE_EXTRA_DIURNO" NUMERIC(5,2) NULL,
	"HD_PORCENTAJE_EXTRA_NOCTURNO" NUMERIC(5,2) NULL,
	"HD_PORCENTAJE_EXTRA_EXTENDIDO" NUMERIC(5,2) NULL,
	"HD_ADICIONADO_POR" VARCHAR(18) NULL,
	"HD_FECHA_ADICION" DATE NULL,
	"HD_MODIFICADO_POR" VARCHAR(18) NULL,
	"HD_FECHA_MODIFICACION" DATE NULL,
	PRIMARY KEY ( "HD_CODIGO_HORARIO" ASC, "HD_CODIGO_EMPRESA" ASC, "HD_DIA" ASC )
) IN "system";


CREATE TRIGGER "TRG_INS_DETALLE_HORARIO" before insert order 1 on
DBA.H_DETALLE_HORARIOS
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial integer;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.HD_CODIGO_AGENCIA=filial;
  set new_name.HD_CODIGO_EMPRESA=compania;
 -- select func_llaves('HH_CODIGO_HORARIO',filial) into numero from SYS.DUMMY;
 -- set new_name.HH_CODIGO_HORARIO=numero;
  set new_name.HD_ADICIONADO_POR=current user;
  set new_name.HD_FECHA_ADICION=current timestamp
end;
CREATE TRIGGER "TRG_UPD_DETALLE_HORARIO" before update order 2 on
DBA.H_DETALLE_HORARIOS
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.HD_MODIFICADO_POR=current user;
  set new_name.HD_FECHA_MODIFICACION=current timestamp
end;


CREATE TABLE "DBA"."H_ENTRADAS_SALIDAS" (
	"HES_CODIGO_EMPRESA" INTEGER NOT NULL,
	"HES_CODIGO_AGENCIA" INTEGER NOT NULL,
	"HES_NUMERO_LOTE" INTEGER NOT NULL,
	"HES_FECHA_LOTE" DATE NULL,
	"HES_CODIGO_BIOMETRICO" VARCHAR(15) NOT NULL,
	"HES_CODIGO_EMPLEADO" INTEGER NOT NULL,
	"HES_CODIGO_NOMBRE" VARCHAR(200) NULL,
	"HES_FECHA" DATE NOT NULL,
	"HES_HORA_ENTRADA" VARCHAR(5) NULL,
	"HES_HORA_SALIDA" VARCHAR(5) NULL,
	"HES_DIA" NUMERIC(1,0) NOT NULL,
	"HES_CANTIDAD_HORAS_ENTRADA" NUMERIC(10,2) NULL,
	"HES_CANTIDAD_HORAS_SALIDA" NUMERIC(10,2) NULL,
	"HES_HORAS_DIURNAS" NUMERIC(10,2) NULL,
	"HES_HORAS_NOCTURNAS" NUMERIC(10,2) NULL,
	"HES_HORAS_EXTRAORDINARIAS" NUMERIC(10,2) NULL,
	"HES_MONTO_DIURNAS" NUMERIC(10,2) NULL,
	"HES_MONTO_NOCTURNAS" NUMERIC(10,2) NULL,
	"HES_MONTO_EXTRAORDINARIAS" NUMERIC(10,2) NULL,
	"HES_ESTADO" VARCHAR(1) NULL,
	"HES_ADICIONADO_POR" VARCHAR(18) NULL,
	"HES_FECHA_ADICION" DATE NULL,
	"HES_MODIFICADO_POR" VARCHAR(18) NULL,
	"HES_FECHA_MODIFICACION" DATE NULL,
	PRIMARY KEY ( "HES_CODIGO_EMPRESA" ASC, "HES_CODIGO_BIOMETRICO" ASC, "HES_FECHA" ASC )
) IN "system";

CREATE TABLE "DBA"."H_HORARIOS" (
	"HH_CODIGO_EMPRESA" INTEGER NOT NULL,
	"HH_CODIGO_AGENCIA" INTEGER NOT NULL,
	"HH_CODIGO_HORARIO" INTEGER NOT NULL,
	"HH_DESCRIPCION" VARCHAR(300) NULL,
	"HH_TIPO_HORARIO" INTEGER NULL,
	"HH_ESTADO" VARCHAR(1) NULL,
	"HH_ADICIONADO_POR" VARCHAR(18) NULL,
	"HH_FECHA_ADICION" DATE NULL,
	"HH_MODIFICADO_POR" VARCHAR(18) NULL,
	"HH_FECHA_MODIFICACION" DATE NULL,
	PRIMARY KEY ( "HH_CODIGO_HORARIO" ASC, "HH_CODIGO_EMPRESA" ASC )
) IN "system";


CREATE TRIGGER "TRG_INS_TIPO_HORARIO" before insert order 1 on
DBA.H_HORARIOS
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial integer;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.HH_CODIGO_AGENCIA=filial;
  set new_name.HH_CODIGO_EMPRESA=compania;
 -- select func_llaves('HH_CODIGO_HORARIO',filial) into numero from SYS.DUMMY;
  --set new_name.HH_CODIGO_HORARIO=numero;
  set new_name.HH_ADICIONADO_POR=current user;
  set new_name.HH_FECHA_ADICION=current timestamp
end;
CREATE TRIGGER "trg_upd_tipo_HORARIO" before update order 2 on
DBA.H_HORARIOS
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.HH_MODIFICADO_POR=current user;
  set new_name.HH_FECHA_MODIFICACION=current timestamp
end;

CREATE TABLE "DBA"."H_PARAMETROS_VACACIONES" (
	"HPV_CODIGO_EMPRESA" INTEGER NOT NULL,
	"HPV_CODIGO_AGENCIA" INTEGER NOT NULL,
	"HPV_SECUENCIA" INTEGER NOT NULL,
	"HPV_CANTIDAD_ANIOS" NUMERIC(10,0) NOT NULL,
	"HPV_CANTIDAD_DIAS_VACACIONES" NUMERIC(10,0) NOT NULL,
	"HPV_CANTIDAD_DIAS_BONO" NUMERIC(10,0) NOT NULL,
	"HPV_ADICIONADO_POR" VARCHAR(18) NULL,
	"HPV_FECHA_ADICION" DATE NULL,
	"HPV_MODIFICADO_POR" VARCHAR(18) NULL,
	"HPV_FECHA_MODIFICACION" DATE NULL,
	PRIMARY KEY ( "HPV_CANTIDAD_ANIOS" ASC, "HPV_CODIGO_EMPRESA" ASC )
) IN "system";

CREATE TRIGGER "TRG_INS_PAR_VAC" before insert order 2 on
DBA.H_PARAMETROS_VACACIONES
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial smallint;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.HPV_CODIGO_EMPRESA=compania;
  set new_name.HPV_CODIGO_AGENCIA=filial;
  select func_llaves('HPV_SECUENCIA',filial) into numero from SYS.DUMMY;
  set new_name.HPV_SECUENCIA=numero;
  set new_name.HPV_ADICIONADO_POR=current user;
  set new_name.HPV_FECHA_ADICION=current date
end;
CREATE TRIGGER "TRG_UPD_PAR_VAC" before update order 3 on
DBA.H_PARAMETROS_VACACIONES
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.HPV_MODIFICADO_POR=current user;
  set new_name.HPV_FECHA_MODIFICACION=current date
end;

CREATE TABLE "DBA"."H_SOLICITUD_VACACIONES" (
	"HSV_CODIGO_EMPRESA" INTEGER NOT NULL,
	"HSV_SECUENCIA" INTEGER NOT NULL,
	"HSV_CODIGO_EMPLEADO" INTEGER NOT NULL,
	"HSV_FECHA" DATE NULL,
	"HSV_FECHA_INICIO" DATE NULL,
	"HSV_FECHA_FIN" DATE NULL,
	"HSV_DIAS" NUMERIC(10,2) NOT NULL,
	"HSV_OBSERVACIONES" VARCHAR(300) NULL,
	"HSV_ESTADO" VARCHAR(1) NULL,
	"HSV_ADICIONADO_POR" VARCHAR(18) NULL,
	"HSV_FECHA_ADICION" DATE NULL,
	"HSV_MODIFICADO_POR" VARCHAR(18) NULL,
	"HSV_FECHA_MODIFICACION" DATE NULL,
	PRIMARY KEY ( "HSV_SECUENCIA" ASC, "HSV_CODIGO_EMPRESA" ASC )
) IN "system";


CREATE TRIGGER "TRG_INS_SOL_VAC" before insert order 2 on
DBA.H_SOLICITUD_VACACIONES
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial smallint;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.HSV_CODIGO_EMPRESA=compania;
  --set new_name.HSV_CODIGO_AGENCIA=filial;
  select func_llaves('H_SOLICITUD_VACACIONES.HSV_SECUENCIA',filial) into numero from SYS.DUMMY;
  set new_name.HSV_SECUENCIA=numero;
  set new_name.HSV_ADICIONADO_POR=current user;
  set new_name.HSV_FECHA_ADICION=current date
end;
CREATE TRIGGER "TRG_UPD_SOL_VAC" before update order 3 on
DBA.H_SOLICITUD_VACACIONES
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.HSV_MODIFICADO_POR=current user;
  set new_name.HSV_FECHA_MODIFICACION=current date
end;

CREATE TABLE "DBA"."H_TIPOS_JORNADA" (
	"HTJ_CODIGO_EMPRESA" INTEGER NOT NULL,
	"HTJ_SECUENCIA" INTEGER NOT NULL,
	"HTJ_DESCRIPCION" VARCHAR(300) NULL,
	"HTJ_ESTADO" VARCHAR(1) NULL,
	"HTJ_ADICIONADO_POR" VARCHAR(18) NULL,
	"HTJ_FECHA_ADICION" DATE NULL,
	"HTJ_MODIFICADO_POR" VARCHAR(18) NULL,
	"HTJ_FECHA_MODIFICACION" DATE NULL,
	PRIMARY KEY ( "HTJ_SECUENCIA" ASC, "HTJ_CODIGO_EMPRESA" ASC )
) IN "system";

CREATE TRIGGER "TRG_INS_TIPO_JORNADA" before insert order 2 on
DBA.H_TIPOS_JORNADA
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial smallint;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.HTJ_CODIGO_EMPRESA=compania;
  --set new_name.HTJ_CODIGO_AGENCIA=filial;
--  select func_llaves('HTJ_SECUENCIA',filial) into numero from SYS.DUMMY;
  --set new_name.HTJ_SECUENCIA=numero;
  set new_name.HTJ_ADICIONADO_POR=current user;
  set new_name.HTJ_FECHA_ADICION=current date
end;
CREATE TRIGGER "TRG_UPD_TIPO_JORNADA" before update order 3 on
DBA.H_TIPOS_JORNADA
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.HTJ_MODIFICADO_POR=current user;
  set new_name.HTJ_FECHA_MODIFICACION=current date
end;

CREATE TABLE "DBA"."H_TIPOS_PLANILLA" (
	"HTP_CODIGO_EMPRESA" INTEGER NOT NULL,
	"HTP_CODIGO_TIPO_PLANILLA" INTEGER NOT NULL,
	"HTP_DESCRIPCION" VARCHAR(300) NULL,
	"HTP_ESTADO" VARCHAR(1) NULL,
	"HTP_PERIOCIDADD" VARCHAR(1) NULL,
	"HTP_TIPO_PAGO" VARCHAR(1) NULL,
	"HTP_CTA_PLANILLA" VARCHAR(20) NULL,
	"HTP_ADICIONADO_POR" VARCHAR(18) NULL,
	"HTP_FECHA_ADICION" DATE NULL,
	"HTP_MODIFICADO_POR" VARCHAR(18) NULL,
	"HTP_FECHA_MODIFICACION" DATE NULL,
	PRIMARY KEY ( "HTP_CODIGO_TIPO_PLANILLA" ASC, "HTP_CODIGO_EMPRESA" ASC )
) IN "system";

CREATE TRIGGER "TRG_INS_TIPOS_PLANILLA" before insert order 1 on
DBA.H_TIPOS_PLANILLA
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare numero decimal(15);
  declare filial integer;
  declare compania smallint;
  select USU_FILIAL,USU_COMPANIA into filial,compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.HTP_CODIGO_EMPRESA=compania;
  set new_name.HTP_ADICIONADO_POR=current user;
  set new_name.HTP_FECHA_ADICION=current timestamp
end;
CREATE TRIGGER "TRG_UPD_TIPOS_PLANILLA" before update order 2 on
DBA.H_TIPOS_PLANILLA
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.HTP_MODIFICADO_POR=current user;
  set new_name.HTP_FECHA_MODIFICACION=current timestamp
end;

CREATE TABLE "DBA"."HISTO_RIES_RNG" (
	"RNG_CLASE" VARCHAR(1) NULL,
	"RNG_CLAVE" INTEGER NULL,
	"RNG_VL1" DECIMAL(10,2) NULL,
	"RNG_VL2" DECIMAL(10,2) NULL,
	"RNG_VL3" DECIMAL(10,2) NULL,
	"RNG_VL4" DECIMAL(10,2) NULL,
	"RNG_VL5" DECIMAL(10,2) NULL,
	"RNG_VL6" DECIMAL(10,2) NULL,
	"RNG_VL7" DECIMAL(10,2) NULL,
	"RNG_CTAS" INTEGER NULL,
	"RNG_NI1" INTEGER NULL,
	"RNG_NI2" INTEGER NULL,
	"RNG_NI3" INTEGER NULL,
	"RNG_MENORES" DECIMAL(10,2) NULL,
	"RNG_MONEDA" VARCHAR(1) NULL,
	"TIEMPO" TIMESTAMP NULL,
	"HECHO" VARCHAR(16) NULL,
	"RNG_COMPANIA" TINYINT NULL
) IN "system";

CREATE TABLE "DBA"."parametros_castigo" (
	"PARCAST_DESTINO" INTEGER NOT NULL,
	"PARCAST_TIPO" TINYINT NULL,
	"PARCAST_CTA_CAP" CHAR(50) NULL,
	"PARCAST_CTA_INT" CHAR(50) NULL,
	"PARCAST_CTA_GASTO" CHAR(50) NULL,
	"PARCAST_CTA_CCPA" CHAR(50) NULL,
	"PARCAST_CTA_CCPAC" CHAR(50) NULL,
	"PARCAST_CTA_CONTRA" CHAR(50) NULL,
	"PARCAST_CTA_IRPA" CHAR(50) NULL,
	"PARCAST_CTA_IRPAC" CHAR(50) NULL,
	"PARCAST_AGREGO" CHAR(20) NULL,
	"PARCAST_FECHA_AGREGO" DATE NULL,
	"PARCAST_MODIFICO" CHAR(20) NULL,
	"PARCAST_FECHA_MODIFI" DATE NULL,
	"PARCAST_COMPANIA" TINYINT NULL,
	PRIMARY KEY ( "PARCAST_DESTINO" ASC )
) IN "system";
CREATE TRIGGER "TRG_UPD_PARAM_CASTIGO" before update on
DBA.parametros_castigo
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  set new_name.PARCAST_MODIFICO=current user;
  set new_name.PARCAST_FECHA_MODIFI=current timestamp
end;
CREATE TRIGGER "TRG_INS_PARAM_CASTIGO" before insert order 1 on
DBA.parametros_castigo
referencing new as new_name
for each row
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
  declare filial smallint;
  declare compania smallint;
  declare numero decimal(15);
  select USU_COMPANIA into compania from DBA.Usuarios where USU_CODIGO = current user;
  set new_name.PARCAST_COMPANIA=compania;
  set new_name.PARCAST_AGREGO=current user;
  set new_name.PARCAST_FECHA_AGREGO=current timestamp
end;


CREATE TABLE "DBA"."PARTE_RELACIONADA" (
	"PR_SEQ" INTEGER NOT NULL,
	"PR_CODIGO_COOP" INTEGER NOT NULL,
	"PR_CODIGO_COOP_PR" INTEGER NOT NULL,
	"PR_NOMBRE_COOP_PR" VARCHAR(50) NOT NULL,
	"PR_COD_PARENTESCO" INTEGER NOT NULL,
	"PR_DESCRIPCION_PAREN" VARCHAR(50) NOT NULL,
	"PR_OBSERVACION" VARCHAR(100) NOT NULL,
	"PR_ESTADO" INTEGER NOT NULL,
	"PR_AGREGO" VARCHAR(50) NOT NULL,
	"PR_FECHA_AGR" DATE NOT NULL,
	"PR_MODIFICO" VARCHAR(50) NULL,
	"PR_FECHA_MOD" DATE NULL,
	"PR_FILIAL" TINYINT NULL,
	"PR_COMPANIA" TINYINT NULL
) IN "system";

CREATE TRIGGER "trg_upd_parte_relac" BEFORE UPDATE
ORDER 1 ON "DBA"."PARTE_RELACIONADA"
REFERENCING OLD AS old_name NEW AS new_name
FOR EACH ROW /* WHEN( search_condition ) */
when(current user <> 'DBA' and current user <> 'USR_SPS')
begin
 set new_name.PR_MODIFICO=current user;
 set new_name.PR_FECHA_MOD=current date;
end;
CREATE TRIGGER "trg_ins_parte_relac" BEFORE INSERT
ORDER 1 ON "DBA"."PARTE_RELACIONADA"
REFERENCING NEW AS new_name
FOR EACH ROW /* WHEN( search_condition ) */
BEGIN
    declare numero decimal(15);
    declare compania smallint;
    if current user <> 'DBA' then
        select USU_COMPANIA into compania from DBA.Usuarios where USU_CODIGO = current user;
        set new_name.PR_COMPANIA=compania;
        if(length(new_name.PR_AGREGO) = 0) or(new_name.PR_AGREGO is null) then
            set new_name.PR_AGREGO=current user;
        end if;
        if new_name.PR_FECHA_AGR is null then
            set new_name.PR_FECHA_AGR=CURRENT DATE;
        end if;
    end if;
END;


CREATE TABLE "DBA"."PROF_ACT_APNFD" (
	"PROACT_CODIGO" INTEGER NOT NULL,
	"PROACT_TIPO" TINYINT NULL,
	"PROACT_SECUENCIA" INTEGER NOT NULL,
	"PROACT_AGREGO" VARCHAR(15) NULL,
	"PROACT_FECHA_AGREGO" DATE NULL,
	"PROACT_MODIFICO" VARCHAR(15) NULL,
	"PROACT_FECHA_MODIFICO" DATE NULL,
	"PROACT_FILIAL" TINYINT NULL,
	"PROACT_COMPANIA" TINYINT NULL,
	PRIMARY KEY ( "PROACT_SECUENCIA" ASC )
) IN "system";



CREATE TABLE "DBA"."USU_RESTR" (
	"Usuario" VARCHAR(30) NOT NULL,
	PRIMARY KEY ( "Usuario" ASC )
) IN "system";

